import type { EnemyDef, WaveEntry } from '../types';
import { FRAMES } from '../config/assets';

/** Enemy bestiary keyed by id. */
export const ENEMIES: Record<string, EnemyDef> = {
  bat: {
    id: 'bat',
    name: 'Cave Bat',
    frame: FRAMES.BAT,
    baseHp: 6,
    contactDamage: 6,
    moveSpeed: 96,
    xp: 1,
    goldChance: 0.01,
    scale: 0.9,
    behavior: 'chase',
    knockbackResist: 0,
  },
  zombie: {
    id: 'zombie',
    name: 'Ghoul',
    frame: FRAMES.ZOMBIE,
    baseHp: 15,
    contactDamage: 8,
    moveSpeed: 56,
    xp: 2,
    goldChance: 0.02,
    scale: 1.1,
    behavior: 'chase',
    knockbackResist: 0.15,
  },
  skeleton: {
    id: 'skeleton',
    name: 'Skeleton',
    frame: FRAMES.SKELETON,
    baseHp: 10,
    contactDamage: 7,
    moveSpeed: 76,
    xp: 2,
    goldChance: 0.02,
    scale: 1.0,
    behavior: 'chase',
    knockbackResist: 0,
  },
  spider: {
    id: 'spider',
    name: 'Cave Spider',
    frame: FRAMES.SPIDER,
    baseHp: 8,
    contactDamage: 9,
    moveSpeed: 112,
    xp: 3,
    goldChance: 0.02,
    scale: 0.95,
    behavior: 'wander-chase',
    knockbackResist: 0,
  },
  cultist: {
    id: 'cultist',
    name: 'Cultist',
    frame: FRAMES.CULTIST,
    baseHp: 24,
    contactDamage: 10,
    moveSpeed: 66,
    xp: 4,
    goldChance: 0.04,
    scale: 1.1,
    behavior: 'chase',
    knockbackResist: 0.1,
  },
  skull: {
    id: 'skull',
    name: 'Flaming Skull',
    frame: FRAMES.SKULL_CRAWLER,
    baseHp: 18,
    contactDamage: 9,
    moveSpeed: 92,
    xp: 4,
    goldChance: 0.03,
    scale: 1.0,
    behavior: 'chase',
    knockbackResist: 0,
  },
  demon: {
    id: 'demon',
    name: 'Imp',
    frame: FRAMES.DEMON,
    tint: 0xff6a4a,
    baseHp: 32,
    contactDamage: 14,
    moveSpeed: 82,
    xp: 6,
    goldChance: 0.05,
    scale: 1.15,
    behavior: 'chase',
    knockbackResist: 0.2,
  },
  // elite — periodically spawned, drops a chest
  mimic: {
    id: 'mimic',
    name: 'Maw of Greed',
    frame: FRAMES.MIMIC,
    baseHp: 240,
    contactDamage: 18,
    moveSpeed: 58,
    xp: 40,
    goldChance: 1,
    scale: 1.6,
    behavior: 'chase',
    knockbackResist: 0.5,
    isElite: true,
  },
  // boss — appears near the end
  reaper: {
    id: 'reaper',
    name: 'The Eternal Night',
    frame: FRAMES.CULTIST,
    tint: 0x6a2cff,
    baseHp: 1500,
    contactDamage: 26,
    moveSpeed: 70,
    xp: 120,
    goldChance: 1,
    scale: 2.3,
    behavior: 'chase',
    knockbackResist: 0.85,
    isBoss: true,
  },

  // event-only: the Ghost Parade (systems/RunEvents) marches these across the
  // arena — never in the wave tables. Fragile, quick, generous with coins.
  wisp: {
    id: 'wisp',
    name: 'Wisp',
    frame: FRAMES.ZOMBIE,
    tint: 0xbfe8ff,
    baseHp: 12,
    contactDamage: 8,
    moveSpeed: 118,
    xp: 4,
    goldChance: 0.3,
    scale: 0.95,
    behavior: 'chase',
    knockbackResist: 0,
  },

  // --- expansion: tinted/rescaled variants reusing chase / wander-chase ---
  wraith: {
    id: 'wraith',
    name: 'Wraith',
    frame: FRAMES.SKELETON,
    tint: 0x9fe8ff,
    baseHp: 9,
    contactDamage: 7,
    moveSpeed: 132,
    xp: 2,
    goldChance: 0.02,
    scale: 0.95,
    behavior: 'wander-chase',
    knockbackResist: 0,
  },
  brute: {
    id: 'brute',
    name: 'Brute',
    frame: FRAMES.ZOMBIE,
    tint: 0x9ab06a,
    baseHp: 60,
    contactDamage: 16,
    moveSpeed: 48,
    xp: 7,
    goldChance: 0.06,
    scale: 1.5,
    behavior: 'chase',
    knockbackResist: 0.4,
  },
  frostDemon: {
    id: 'frostDemon',
    name: 'Frost Imp',
    frame: FRAMES.DEMON,
    tint: 0x6ab0ff,
    baseHp: 40,
    contactDamage: 13,
    moveSpeed: 80,
    xp: 7,
    goldChance: 0.05,
    scale: 1.2,
    behavior: 'chase',
    knockbackResist: 0.25,
  },
  giantSpider: {
    id: 'giantSpider',
    name: 'Broodmother',
    frame: FRAMES.SPIDER,
    tint: 0xb060c0,
    baseHp: 30,
    contactDamage: 11,
    moveSpeed: 96,
    xp: 5,
    goldChance: 0.04,
    scale: 1.4,
    behavior: 'wander-chase',
    knockbackResist: 0.1,
  },
  revenant: {
    id: 'revenant',
    name: 'Revenant',
    frame: FRAMES.CULTIST,
    tint: 0x88ff9a,
    baseHp: 34,
    contactDamage: 12,
    moveSpeed: 72,
    xp: 6,
    goldChance: 0.05,
    scale: 1.1,
    behavior: 'chase',
    knockbackResist: 0.15,
  },
  boneLord: {
    id: 'boneLord',
    name: 'Bone Lord',
    frame: FRAMES.SKULL_CRAWLER,
    tint: 0xfff0c0,
    baseHp: 340,
    contactDamage: 18,
    moveSpeed: 64,
    xp: 50,
    goldChance: 1,
    scale: 1.7,
    behavior: 'chase',
    knockbackResist: 0.5,
    isElite: true,
  },
  demonKing: {
    id: 'demonKing',
    name: 'Demon King',
    frame: FRAMES.DEMON,
    tint: 0xc01818,
    baseHp: 1100,
    contactDamage: 24,
    moveSpeed: 66,
    xp: 100,
    goldChance: 1,
    scale: 2.2,
    behavior: 'chase',
    knockbackResist: 0.8,
    isBoss: true,
  },
};

/**
 * Wave schedule. The spawner picks the latest entry whose `timeSec` has passed.
 * `bossId` (if present) is spawned once when that wave first activates.
 * Victory is reached at RUN.SURVIVE_MS (8:00).
 */
export const WAVES: WaveEntry[] = [
  { timeSec: 0, enemies: ['bat'], cap: 40, spawnIntervalSec: 1.1, burst: 3 },
  { timeSec: 40, enemies: ['bat', 'zombie'], cap: 60, spawnIntervalSec: 1.0, burst: 4 },
  { timeSec: 80, enemies: ['bat', 'zombie', 'skeleton'], cap: 80, spawnIntervalSec: 0.9, burst: 5 },
  {
    timeSec: 130,
    enemies: ['zombie', 'skeleton', 'wraith'],
    cap: 100,
    spawnIntervalSec: 0.85,
    burst: 6,
    bossId: 'mimic',
  },
  {
    timeSec: 180,
    enemies: ['skeleton', 'wraith', 'spider', 'revenant'],
    cap: 120,
    spawnIntervalSec: 0.8,
    burst: 7,
  },
  {
    timeSec: 230,
    enemies: ['spider', 'giantSpider', 'cultist', 'revenant'],
    cap: 140,
    spawnIntervalSec: 0.75,
    burst: 8,
    bossId: 'boneLord',
  },
  {
    timeSec: 290,
    enemies: ['cultist', 'skull', 'frostDemon', 'wraith'],
    cap: 160,
    spawnIntervalSec: 0.7,
    burst: 9,
  },
  {
    timeSec: 350,
    enemies: ['skull', 'frostDemon', 'demon', 'brute'],
    cap: 180,
    spawnIntervalSec: 0.66,
    burst: 10,
    bossId: 'demonKing',
  },
  {
    // The final boss now arrives here (was 450s) so it gets a real ~70s
    // engagement window before RUN.SURVIVE_MS ends the run, instead of ~30s.
    timeSec: 410,
    enemies: ['demon', 'brute', 'revenant', 'giantSpider'],
    cap: 200,
    spawnIntervalSec: 0.62,
    burst: 11,
    bossId: 'reaper',
  },
  {
    timeSec: 450,
    enemies: ['demon', 'frostDemon', 'brute', 'skull'],
    cap: 220,
    spawnIntervalSec: 0.58,
    burst: 13,
  },
];
